image: python:latest

before_script:
    - python3 -V

stages:
    - test
    - lint

test-job:
    stage: test
    
    before_script: 
        - cd backend
        - python3 -m pip install -r requirements.txt
        - python3 -m pip install coverage
    
    script:
        - coverage run manage.py test
        - coverage report > report.txt
        - mkdir public
        - mv report.txt ./public
    
    artifacts:
        paths:
            - ./public

pylint-job:
    stage: lint

    before_script:
        - cd backend
        - python3 -m pip install -r requirements.txt
        - python3 -m pip install pylint
    
    script:
        - find . -type f -name "*.py" | xargs pylint 
