image: python:latest

cache:
  paths:
  - ~/.cache/pip/

before_script:
  - python -V

stages:
  - test
  - autopep8
  - lint

autopep8-job:
  stage: autopep8
  before_script:
  - pip install -r ci/autopep8_requirements.txt
  script:
  - chmod +x ./ci/autopep8_runner.sh
  - ./ci/autopep8_runner.sh

pylint:
  stage: lint
  before_script:
  - pip install -r ci/pylint_requirements.txt
  script:
  - chmod +x ./ci/pylint_runner.sh
  - ./ci/pylint_runner.sh
  artifacts:
    paths:
      - backend/public/pylint.svg
      - backend/public/pylint.html

test:
  stage: test
  before_script:
  - cd backend
  - pip install coverage
  - pip install -r requirements.txt
  script:
  - coverage run manage.py test
  - coverage report --omit=manage.py
  - coverage html --omit=manage.py
  - mkdir public
  - mv htmlcov public/coverage
  artifacts:
    paths:
      - public/coverage
