# Generated by Django 3.2.9 on 2022-03-13 12:53

from django.db import migrations


def create_account_types(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    AccountType = apps.get_model("urmusic_api", "AccountType")
    if not AccountType.objects.using(db_alias).filter(id=1).count():
        AccountType.objects.using(db_alias).create(id=1, name="user")
    if not AccountType.objects.using(db_alias).filter(id=2).count():
        AccountType.objects.using(db_alias).create(id=2, name="object_owner")
    if not AccountType.objects.using(db_alias).filter(id=3).count():
        AccountType.objects.using(db_alias).create(id=3, name="admin")


class Migration(migrations.Migration):

    dependencies = [
        ('urmusic_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_account_types)
    ]
