# Generated by Django 3.2.9 on 2022-03-20 12:48

from django.db import migrations

from urmusic_api import models


def create_admin_user(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    User = apps.get_model("urmusic_api", "User")
    if not User.objects.using(db_alias).filter(id=1).count():
        models.User.create_super_user()


class Migration(migrations.Migration):

    dependencies = [
        ('urmusic_api', '0003_auto_20220320_1548'),
    ]

    operations = [
        migrations.RunPython(create_admin_user)
    ]
