# Generated by Django 3.2.9 on 2022-03-23 14:40

from django.db import migrations


def update_admin_user(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    User = apps.get_model("urmusic_api", "User")
    if User.objects.using(db_alias).filter(id=1).count():
        user = User.objects.using(db_alias).filter(id=1).first()
        user.city = "Москва"
        user.first_name = "Админ"
        user.last_name = "Админов"
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('urmusic_api', '0005_auto_20220323_1740'),
    ]

    operations = [
        migrations.RunPython(update_admin_user)
    ]
