# Generated by Django 3.2.9 on 2022-03-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urmusic_api', '0008_auto_20220324_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='file',
            field=models.FileField(null=True, upload_to='tracks/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.TextField(),
        ),
    ]
