# Generated by Django 3.2.9 on 2022-03-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urmusic_api', '0009_auto_20220324_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='vk_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
