# Generated by Django 3.2.9 on 2022-03-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urmusic_api', '0010_auto_20220325_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
