# Generated by Django 3.2.13 on 2022-05-28 21:59
import json

from dadata import Dadata
from django.conf import settings
from django.db import migrations


def create_restaurants(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Restaurant = apps.get_model("urmusic_api", "Restaurant")
    User = apps.get_model("urmusic_api", "User")
    admin_user = User.objects.using(db_alias).filter(id=1).first()
    with open("urmusic_api/migrations/data/restaurants.json", encoding="utf-8") as f:
        restaurant_data = json.load(f)
    for restaurant in restaurant_data:
        if not Restaurant.objects.using(db_alias).filter(name=restaurant["Name"]).count():
            dadata = Dadata(settings.DADATA_TOKEN)
            try:
                assert dadata.suggest("address", restaurant["Address"])[0]
                Restaurant.objects.using(db_alias).create(name=restaurant["Name"],
                                                          description=restaurant["TypeObject"],
                                                          address=restaurant["Address"],
                                                          owner=admin_user)
            except:
                pass


class Migration(migrations.Migration):
    dependencies = [
        ('urmusic_api', '0013_alter_restaurant_image'),
    ]

    operations = [
        migrations.RunPython(create_restaurants)
    ]
