# Generated by Django 3.2.13 on 2022-05-28 22:24
import json

from django.core.files import File
from django.core.files.temp import NamedTemporaryFile
from django.db import migrations


def create_tracks(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Track = apps.get_model("urmusic_api", "Track")
    with open("urmusic_api/migrations/data/music/music.json", encoding="utf-8") as f:
        track_data = json.load(f)
    for track in track_data:
        if not Track.objects.using(db_alias).filter(title=track["title"]).count():
            track_object = Track.objects.using(db_alias).create(title=track["title"],
                                                                artist=track["artist"])
            file_temp = NamedTemporaryFile()
            with open(f"urmusic_api/migrations/data/music/{track['file']}", "rb") as f:
                file_temp.write(f.read())
            file_temp.flush()
            track_object.file.save(track["file"], File(file_temp), save=True)
            track_object.save()


class Migration(migrations.Migration):
    dependencies = [
        ('urmusic_api', '0014_auto_20220528_2159'),
    ]

    operations = [
        migrations.RunPython(create_tracks)
    ]
